controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class NewsController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}

	/**
	 * Displays view page.
	 *
	 * @return Response|string
	 */
	public function actionView($id)
	{
		$this->view->title = 'Single Post';
		return $this->render('view');
	}
}

views/news/_section/_about.php
<?php
use yii\helpers\Url;
?>
<div class="cell-sm-6 cell-md-12">
	<div class="decorative">
		<div class="decorative decorative-md">
			<h5 class="decorative-title">About</h5>
			<div class="sidebar-description">
				<p>Over the last 13 years, GardenLand has created numerous award-winning luxury outdoor living areas. Today we specialize not only in landscape design, but also in other exterior services.</p><a class="post-link" href="<?= Url::to(['site/about']) ?>">Read More</a>
			</div>
		</div>
	</div>
</div>

views/news/_section/_archive.php
<div class="cell-sm-6 cell-md-12">
	<div class="decorative">
		<div class="decorative decorative-md">
			<h5 class="decorative-title">Archive</h5>
			<ul class="list-marked list-marked-1">
				<li><a href="#">November 2017</a></li>
				<li><a href="#">October 2017</a></li>
				<li><a href="#">September 2017</a></li>
				<li><a href="#">August 2017</a></li>
				<li><a href="#">July 2017</a></li>
				<li><a href="#">June 2017</a></li>
			</ul>
		</div>
	</div>
</div>

views/news/_section/_articles.php
<?php
use yii\helpers\Url;
?>
<section>
	<!-- Post Classic-->
	<article class="post post-classic">
		<!-- Post media--><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img class="img-responsive" src="/images/post-classic-1-960x500.jpg" alt="" width="960" height="500"/></a>
		<!-- Post content-->
		<section class="post-content text-left">
			<div class="decorative decorative-lg">
				<h3 class="decorative-title"><a class="link-gray-dark" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Winners of Best Landscape for Summer  2017: Latest Results and Comments</a></h3>
				<ul class="post-meta list-dotted">
					<li>
						<time datetime="2017-01-01">January 22, 2017</time>
					</li>
					<li><span class="text-base">by:</span> <a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
					</li>
					<li><a class="link" href="#">News</a>
					</li>
					<li><a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">12 <span class="text-base">Comments</span></a></li>
				</ul>
				<p class="post-description">Annual survey and analysis of community of over 35 million monthly users reveals the top-rated home remodeling professionals and most popular landscape designs. Houzz Inc., the leading platform for home renovation and design, today announced the community’s picks for Best Landscape 2016 in North America, a homeowner-to-homeowner guide to the top...</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read More</a>
			</div>
		</section>
	</article>
	<!-- Post Classic-->
	<article class="post post-classic">
		<!-- Post media--><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img class="img-responsive" src="/images/post-classic-2-960x500.jpg" alt="" width="960" height="500"/></a>
		<!-- Post content-->
		<section class="post-content text-left">
			<div class="decorative decorative-lg">
				<h3 class="decorative-title"><a class="link-gray-dark" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Triple Victory at Inaugural WA Landscape  Design Awards</a></h3>
				<ul class="post-meta list-dotted">
					<li>
						<time datetime="2017-01-01">January 20, 2017</time>
					</li>
					<li><span class="text-base">by:</span> <a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
					</li>
					<li><a class="link" href="#">News</a>
					</li>
					<li><a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">12 <span class="text-base">Comments</span></a></li>
				</ul>
				<p class="post-description">The awards aimed to recognise and showcase the very best landscape design projects in WA. We were thrilled to achieve an award for all three categories we entered into.  We had some very demanding, yet professional judges who are also well-respected landscape designers and media identities. They have also picked other favorites that we would like to notice as well. These...</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read More</a>
			</div>
		</section>
	</article>
	<!-- Post Classic-->
	<article class="post post-classic">
		<!-- Post media--><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img class="img-responsive" src="/images/post-classic-3-960x500.jpg" alt="" width="960" height="500"/></a>
		<!-- Post content-->
		<section class="post-content text-left">
			<div class="decorative decorative-lg">
				<h3 class="decorative-title"><a class="link-gray-dark" href="<?= Url::to(['news/view', 'id' => 5]) ?>">The Right Stone for your Garden Design: Our List of the Top 3 Recommendations</a></h3>
				<ul class="post-meta list-dotted">
					<li>
						<time datetime="2017-01-01">January 18, 2017</time>
					</li>
					<li><span class="text-base">by:</span> <a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
					</li>
					<li><a class="link" href="#">News</a>
					</li>
					<li><a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">12 <span class="text-base">Comments</span></a></li>
				</ul>
				<p class="post-description">Stone has always been a cost-effective hardscape material for all garden styles. Nowadays they are used as an affordable and easy-to-install surface in contemporary gardens. Their larger relations, the pebbles, cobbles and paddle stones, have become a much more interesting and useful material in our gardens, as they have so many applications.</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read More</a>
			</div>
		</section>
	</article>
	<!-- Post Classic-->
	<article class="post post-classic">
		<!-- Post media--><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img class="img-responsive" src="/images/post-classic-4-960x500.jpg" alt="" width="960" height="500"/></a>
		<!-- Post content-->
		<section class="post-content text-left">
			<div class="decorative decorative-lg">
				<h3 class="decorative-title"><a class="link-gray-dark" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Why Exterior Design is Important</a></h3>
				<ul class="post-meta list-dotted">
					<li>
						<time datetime="2017-01-01">January 22, 2017</time>
					</li>
					<li><span class="text-base">by:</span> <a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
					</li>
					<li><a class="link" href="#">News</a>
					</li>
					<li><a class="link link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">12 <span class="text-base">Comments</span></a></li>
				</ul>
				<p class="post-description">It is vital to have the house look attractive from the outside, as it is the face of you and your family. In some way it gives a picture of the people who live in it, their likes, hobbies, etc. So a good exterior is as important as a proper interior. There are hundreds designs and styles used in landscape.</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read More</a>
			</div>
		</section>
	</article><a class="button button-primary button-icon button-icon-left" href="#"><span class="icon fa-refresh"></span>Load more posts</a>
</section>

views/news/_section/_author-info.php
<section class="section-lg bg-white">
	<div class="decorative decorative-lg">
		<h3 class="decorative-title">Author</h3>
		<article class="blurb-author">
			<div class="unit unit-spacing-md unit-xs-horizontal">
				<div class="unit__left"><img src="/images/news-author-190x190.jpg" alt="" width="190" height="190"/>
				</div>
				<div class="unit__body">
					<h5 class="blurb-author-title">Kevin Wade</h5>
					<p class="blurb-author-position">Blogger</p>
					<p class="blurb-author-text">I am a professional blogger interested in everything taking place in cyberspace. I am running this website and try my best to make it a better place to visit. I post only the articles that are related to the topic and thoroughly analyze all visitors’ comments to cater to their needs better.</p>
				</div>
			</div>
		</article>
	</div>
</section>

views/news/_section/_categories.php
<div class="cell-sm-6 cell-md-12">
	<div class="decorative">
		<div class="decorative decorative-md">
			<h5 class="decorative-title">Categories</h5>
			<ul class="list-marked list-marked-1">
				<li><a href="#">News</a></li>
				<li><a href="#">Design</a></li>
				<li><a href="#">Garden Sculptures</a></li>
				<li><a href="#">Landscape Design</a></li>
				<li><a href="#">Review</a></li>
				<li><a href="#">Exterior</a></li>
			</ul>
		</div>
	</div>
</div>

views/news/_section/_comments-form.php
<section class="section-lg bg-white">
	<div class="decorative decorative-lg">
		<h3 class="decorative-title">Send a Comment</h3>
		<!-- RD Mailform-->
		<form class="rd-mailform text-left" data-form-output="form-output-global" data-form-type="forms" method="post" action="bat/rd-mailform.php">
			<div class="range range-xs-center range-15">
				<div class="cell-sm-6">
					<div class="form-wrap form-wrap-validation">
						<label class="form-label form-label-outside" for="forms-name">First name</label>
						<input class="form-input" id="forms-name" type="text" name="name" data-constraints="@Required">
					</div>
				</div>
				<div class="cell-sm-6">
					<div class="form-wrap form-wrap-validation">
						<label class="form-label form-label-outside" for="forms-last-name">Last name</label>
						<input class="form-input" id="forms-last-name" type="text" name="last-name" data-constraints="@Required">
					</div>
				</div>
				<div class="cell-sm-6">
					<div class="form-wrap form-wrap-validation">
						<label class="form-label form-label-outside" for="forms-email">E-mail</label>
						<input class="form-input" id="forms-email" type="email" name="email" data-constraints="@Email @Required">
					</div>
				</div>
				<div class="cell-sm-6">
					<div class="form-wrap form-wrap-validation">
						<label class="form-label form-label-outside" for="forms-phone">Phone</label>
						<input class="form-input" id="forms-phone" type="text" name="phone" data-constraints="@Numeric @Required">
					</div>
				</div>
				<div class="cell-sm-12">
					<div class="form-wrap form-wrap-validation">
						<label class="form-label form-label-outside" for="forms-message">Message</label>
						<textarea class="form-input" id="forms-message" name="message" data-constraints="@Required"></textarea>
					</div>
				</div>
			</div>
			<div class="form-button">
				<button class="button button-primary" type="submit">Submit</button>
			</div>
		</form>
	</div>
</section>

views/news/_section/_fb-block.php
<div class="cell-sm-6 cell-md-12">
	<!-- Facebook Feed-->
	<div id="fb-root"></div>
	<div class="fb-page-responsive">
		<div class="fb-page" data-href="https://www.facebook.com/TemplateMonster" data-tabs="timeline" data-height="500" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
			<div class="fb-xfbml-parse-ignore">
				<blockquote cite="https://www.facebook.com/TemplateMonster"><a href="https://www.facebook.com/TemplateMonster">TemplateMonster</a></blockquote>
			</div>
		</div>
	</div>
</div>

views/news/_section/_gallery.php
<div class="cell-sm-6 cell-md-12">
	<div class="decorative">
		<div class="decorative decorative-md">
			<h5 class="decorative-title">Gallery</h5>
			<ul class="gallery-custom" data-photo-swipe-gallery="gallery">
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="1200x800" href="/images/gallery-image-original-13-1200x800.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-1-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="1200x778" href="/images/gallery-image-original-14-1200x778.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-2-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="1200x797" href="/images/gallery-image-original-15-1200x797.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-3-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="923x800" href="/images/gallery-image-original-16-923x800.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-4-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="1200x800" href="/images/gallery-image-original-17-1200x800.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-5-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
				<li><a class="thumbnail-classic" data-photo-swipe-item="" data-size="1200x800" href="/images/gallery-image-original-7-1200x800.jpg">
						<div class="thumbnail-overlay"><img src="/images/aside-gallery-6-140x140.jpg" alt="" width="140" height="140"/>
						</div></a>
				</li>
			</ul>
		</div>
	</div>
</div>

views/news/_section/_latest-home.php
<?php
use yii\helpers\Url;
?>
<section class="section section-sm bg-white">
	<div class="shell shell-fluid">
		<div class="range range-30 range-center range-md-justify range-xl-condensed">
			<div class="cell-sm-9 cell-md-5 cell-xl-preffix-1">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">Latest Company News</h3>
				</div>
			</div>
			<div class="cell-sm-9 cell-md-5 text-md-right cell-xl-postfix-1"><a class="button button-primary" href="<?= Url::to(['news/index']) ?>">View all news</a></div>

			<?= $this->render('_same-latest.php') ?>

		</div>
	</div>
</section>

views/news/_section/_latest-other.php
<?php
use yii\helpers\Url;
?>
<section class="section section-sm bg-white">
	<div class="shell shell-fluid">
		<div class="range range-30 range-center range-md-justify range-xl-condensed">
			<div class="cell-sm-10 cell-md-5 cell-xl-preffix-1">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">Latest Blog Posts</h3>
				</div>
			</div>
			<div class="cell-sm-10 cell-md-5 text-md-right cell-xl-postfix-1"><a class="button button-primary" href="<?= Url::to(['news/index']) ?>">View all news</a></div>
		</div>

		<?= $this->render('_same-latest.php') ?>

	</div>
</section>

views/news/_section/_post-content.php
<?php
use yii\helpers\Url;
?>
<section class="post-single-body section-lg bg-white">
	<div class="decorative decorative-lg">
		<h3 class="decorative-title post-heading">Winners of Best Landscape for Summer  2017: Latest Results and Comments</h3>
		<ul class="post-meta list-dotted">
			<li><span class="time">July 22, 2017</span></li>
			<li><span class="author">by Kevin Wade</span></li>
			<li><a class="post-tag" href="<?= Url::toRoute(['news/index']) ?>">News</a></li>
			<li><span class="post-comments">2 Comments</span></li>
		</ul>
	</div><img src="/images/news-single-1-960x500.jpg" alt="" width="960" height="500"/>
	<div class="decorative decorative-lg">
		<p>Annual survey and analysis of community of over 35 million monthly users reveals the top-rated home remodeling professionals and most popular landscape designs.</p>
		<p>Houzz Inc., the leading platform for home renovation and design, today announced the community’s picks for Best Landscape 2016 in North America, a homeowner-to-homeowner guide to the top  interior designers, landscape pros and other residential remodeling professionals on Houzz from cabinetry or roofing pros to painters.</p>
	</div>
	<blockquote class="quote quote-default quote-primary">
		<div class="quote-body">
			<p>
				<q>The results of this year’s “Best Landscape” event were somehow predictable yet amazing. We are glad that our partner, GardenLand, took the first place in this rating. It shows the quality of the services they provide.</q>
			</p>
		</div>
		<div class="quote-meta">
			<div class="unit unit-spacing-xxs unit-middle unit-horizontal text-left">
				<div class="unit__left"><img class="img-circle" src="/images/quote-1-60x60.jpg" alt="" width="60" height="60"/>
				</div>
				<div class="unit__body">
					<cite>Robert Ball</cite><small><span>President of US Landscape Design Corporation,</span><br><span>GardenLand’s partner</span></small>
				</div>
			</div>
		</div>
	</blockquote><img src="/images/news-single-2-960x500.jpg" alt="" width="960" height="500"/>
	<div class="decorative decorative-lg">
		<p>The Best Landscapes Award is presented annually. Award winners’ work was the most popular among the more than 35 million monthly users on Houzz.</p>
		<p>Customer Service honors are based on several factors, including the number and quality of recent client reviews. Architecture and interior design photographers whose images were most popular are recognized with the Photography award. A “Best Of Houzz 2016” badge appears on winners’ profiles, as a sign of their commitment to excellence.</p>
		<div class="range social-section">
			<div class="cell-xl-6">
				<ul class="list-tags">
					<li><a href="#">Design</a></li>
					<li><a href="#">Exterior</a></li>
					<li><a href="#">Event</a></li>
					<li><a href="#">News</a></li>
				</ul>
			</div>
			<div class="cell-xl-6">
				<ul class="list-inline list-inline-sm text-xl-right">
					<li><span>Share This Post!</span></li>
					<li><a class="icon icon-xxs fa fa-facebook" href="#"></a></li>
					<li><a class="icon icon-xxs fa fa-twitter" href="#"></a></li>
					<li><a class="icon icon-xxs fa fa-pinterest" href="#"></a></li>
					<li><a class="icon icon-xxs fa fa-vimeo" href="#"></a></li>
					<li><a class="icon icon-xxs fa fa-google" href="#"></a></li>
					<li><a class="icon icon-xxs fa fa-rss" href="#"></a></li>
				</ul>
			</div>
		</div>
	</div>
</section>

views/news/_section/_recent-post.php
<section class="section-lg bg-white post-single-section">
	<div class="decorative decorative-lg text-center text-xs-left">
		<h3 class="decorative-title">Recent Posts</h3>
		<div class="post-project unit unit-spacing-md unit-xs-horizontal">
			<div class="unit__left"><a href="#"><img src="/images/news-single-3-220x160.jpg" alt="" width="220" height="160"/></a></div>
			<div class="unit__body project-body">
				<div class="project-caption">
					<p class="project-date"><span class="project-date">July 22, 2017</span> <span class="project-time">at 6:35pm</span>
					</p>
					<h6 class="project-title"><a href="#">Triple Victory at Inaugural WA Landscape Design Awards </a></h6>
				</div>
				<div class="project-meta"><span class="comment"><a class="link-gray-dark" href="#">32</a></span><span class="author"><a class="link-gray-dark" href="#">Kevin Wade</a></span></div>
			</div>
		</div>
		<div class="post-project unit unit-spacing-md unit-xs-horizontal">
			<div class="unit__left"><a href="#"><img src="/images/news-single-4-220x160.jpg" alt="" width="220" height="160"/></a></div>
			<div class="unit__body project-body">
				<div class="project-caption">
					<p class="project-date"><span class="project-date">July 22, 2017</span> <span class="project-time">at 6:35pm</span>
					</p>
					<h6 class="project-title"><a href="#">The Right Stone for your Garden Design: Our List of the Top 3 Recommendations</a></h6>
				</div>
				<div class="project-meta"><span class="comment"><a class="link-gray-dark" href="#">32</a></span><span class="author"><a class="link-gray-dark" href="#">Kevin Wade</a></span></div>
			</div>
		</div>
	</div>
</section>

views/news/_section/_same-latest.php
<?php
use yii\helpers\Url;
?>

<div class="range range-50 range-center range-md-justify range-xl-condensed">
	<div class="cell-sm-9 cell-md-4 cell-xl-3 cell-xl-preffix-1">
		<article class="post-default">
			<div class="post-media"><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img src="/images/mission-post-1-480x360.jpg" alt="" width="480" height="360"/></a></div>
			<div class="post-title">
				<div class="decorative decorative-md">
					<h5 class="decorative-title"><a class="text-gray-2" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Winners of Best Landscape for Summer  2017: Latest Results and Comments</a></h5>
					<ul class="post-meta list-dotted">
						<li><span class="time">July 22, 2017</span></li>
						<li class="author">by <a class="link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
						</li>
					</ul>
					<div class="post-content">
						<p>Annual survey and analysis of community of over 35 million monthly users reveals the top-rated home remodeling professionals and most popular landscape designs.</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read more</a>
					</div>
				</div>
			</div>
		</article>
	</div>
	<div class="cell-sm-9 cell-md-4 cell-xl-3">
		<article class="post-default">
			<div class="post-media"><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img src="/images/mission-post-2-480x360.jpg" alt="" width="480" height="360"/></a></div>
			<div class="post-title">
				<div class="decorative decorative-md">
					<h5 class="decorative-title"><a class="text-gray-2" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Triple Victory at Inaugural WA Landscape  Design Awards</a></h5>
					<ul class="post-meta list-dotted">
						<li><span class="time">July 22, 2017</span></li>
						<li class="author">by <a class="link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
						</li>
					</ul>
					<div class="post-content">
						<p>The awards aimed to recognise and showcase the very best landscape design projects in WA. We were thrilled to achieve an award for all three categories we entered into.</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read more</a>
					</div>
				</div>
			</div>
		</article>
	</div>
	<div class="cell-sm-9 cell-md-4 cell-xl-3 cell-xl-postfix-1">
		<article class="post-default">
			<div class="post-media"><a href="<?= Url::to(['news/view', 'id' => 5]) ?>"><img src="/images/mission-post-3-480x360.jpg" alt="" width="480" height="360"/></a></div>
			<div class="post-title">
				<div class="decorative decorative-md">
					<h5 class="decorative-title"><a class="text-gray-2" href="<?= Url::to(['news/view', 'id' => 5]) ?>">The Right Stone for your Garden Design: Our List of the Top 3 Recommendations</a></h5>
					<ul class="post-meta list-dotted">
						<li><span class="time">July 22, 2017</span></li>
						<li class="author">by <a class="link-default" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Kevin Wade</a>
						</li>
					</ul>
					<div class="post-content">
						<p>Stone has always been a cost-effective hardscape material for all garden styles. Nowadays they are used as an affordable and easy-to-install surface in contemporary gardens.</p><a class="post-link" href="<?= Url::to(['news/view', 'id' => 5]) ?>">Read more</a>
					</div>
				</div>
			</div>
		</article>
	</div>
</div>

views/news/_section/_search-form.php
<div class="cell-sm-12 cell-md-12">
	<div class="decorative decorative-md">
		<h5 class="decorative-title">Search</h5>
		<!-- Search Form-->
		<form class="form-search rd-search rd-mailform-inline rd-mailform-small" action="/site/search-results.html" method="GET">
			<div class="form-wrap">
				<label class="form-label form-search-label form-label-sm" for="blog-sidebar-2-form-search-widget">Search</label>
				<input class="form-input form-search-input form-control #{inputClass}" id="blog-sidebar-2-form-search-widget" type="text" name="s" autocomplete="off">
			</div>
			<button class="button button-sm button-primary form-search-submit" type="submit">Search</button>
		</form>
	</div>
</div>