controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class NewsController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}

	/**
	 * Displays view page.
	 *
	 * @return Response|string
	 */
	public function actionView($id)
	{
		$this->view->title = 'Single Post';
		return $this->render('view');
	}
}

controllers/PagesController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class PagesController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
//		$this->view->title = 'Product Catalog';
		return $this->render('index');
	}

	/**
	 * Displays gridgallery page.
	 *
	 * @return Response|string
	 */
	public function actionGridgallery()
	{
		$this->view->title = 'Grid gallery';
		return $this->render('grid-gallery');
	}
}

controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class ProductController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}

	/**
	 * Displays view page.
	 *
	 * @return Response|string
	 */
	public function actionView($id)
	{
		$this->view->title = 'Single Product';
		return $this->render('view');
	}

	/**
	 * Displays productions page.
	 *
	 * @return Response|string
	 */
	public function actionProduction()
	{
		return $this->render('production');
	}
}

views/_section/_areas-of-work.php
<?php
use yii\helpers\Url;
?>
<section class="section section-md bg-white">
	<div class="shell shell-fluid">
		<div class="range range-40 range-xl-condensed">
			<div class="cell-md-7 cell-xl-6 cell-xl-preffix-1">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">Areas of Work</h3>
					<p>When we take your landscaping project, we never waste your time idly…  Quick on getting all the brief on the ideas you might have, we immediately start the working process, making sure that everything gets done ahead of the schedule!</p>
					<div class="range range-40">
						<div class="cell-sm-6 cell-xl-5">
							<div class="blurb">
								<div class="icon icon-primary icon-xxl fl-line-icon-set-plant10"></div>
								<h5 class="blurb-title"><a class="text-gray-darker" href="<?= Url::toRoute(['site/about']) ?>">Landscape Ideas</a></h5>
								<p class="blurb-content">From finding the best landscape design ideas or inspiration to maintaining your dream yard, the landscaping tips and design ideas will keep you moving. </p>
							</div>
						</div>
						<div class="cell-sm-6 cell-xl-5 cell-xl-preffix-1">
							<div class="blurb">
								<div class="icon icon-primary icon-xxl fl-line-icon-set-diamond18"></div>
								<h5 class="blurb-title"><a class="text-gray-darker" href="<?= Url::toRoute(['site/about']) ?>">Architectural Design Coordination</a></h5>
								<p class="blurb-content">Architectural design is typically a multi-staged process, involving a number of designers working together to create a single project that can improve your yard.</p>
							</div>
						</div>
						<div class="cell-sm-6 cell-xl-5">
							<div class="blurb">
								<div class="icon icon-primary icon-xxl fl-line-icon-set-cogwheel8"></div>
								<h5 class="blurb-title"><a class="text-gray-darker" href="<?= Url::toRoute(['site/about']) ?>">Landscape Maintenance</a></h5>
								<p class="blurb-content">We will customize a regular service plan just for your yard, focused on highlighting its natural beauty. We will maintain your landscape so you can enjoy satisfaction.</p>
							</div>
						</div>
						<div class="cell-sm-6 cell-xl-5 cell-xl-preffix-1">
							<div class="blurb">
								<div class="icon icon-primary icon-xxl fl-line-icon-set-square51"></div>
								<h5 class="blurb-title"><a class="text-gray-darker" href="<?= Url::toRoute(['site/about']) ?>">Construction Consultation</a></h5>
								<p class="blurb-content">GardenLand provides comprehensive construction management consulting services that provide the best results for your project, whether it’s commercial or individual.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="cell-md-5 cell-xl-3 cell-xl-preffix-1">
				<div class="thumbnail-type-3"><img src="/images/index-1-480x400.jpg" alt="" width="480" height="400"/>
					<div class="caption">
						<h5 class="text-bold title">About Us</h5>
						<p class="description">Over the last 13 years, GardenLand has created numerous award-winning luxury outdoor living areas. We can complete landscape design projects of various complexity.</p><a class="post-link" href="<?= Url::toRoute(['site/about-us']) ?>">Read more</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

views/_section/_footer-contacts.php
	<h5>Контакты</h5>
	<div class="divider divider-3"></div>
	<div class="range range-40">
		<div class="cell-sm-6">
			<h6>Greenfield Office</h6>
			<div class="decorative decorative-md">
				<ul class="list">
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-map-marker"></span></div>
							<div class="unit__body"><a class="link-default" href="#">995 Green Hill St., Greenfield, IN 46140</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-phone"></span></div>
							<div class="unit__body"><a class="link-default" href="callto:#">1-800-1234-567</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-email-outline"></span></div>
							<div class="unit__body"><a class="link-default" href="mailto:#">mail@demolink.org</a></div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="cell-sm-6">
			<h6>Whitehall Office</h6>
			<div class="decorative decorative-md">
				<ul class="list">
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-map-marker"></span></div>
							<div class="unit__body"><a class="link-default" href="#">273 Johnson Street, Whitehall, PA 18052</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-phone"></span></div>
							<div class="unit__body"><a class="link-default" href="callto:#">1-800-8765-098</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-email-outline"></span></div>
							<div class="unit__body"><a class="link-default" href="mailto:#">mail@demolink.org</a></div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="cell-sm-6">
			<h6>New York Office</h6>
			<div class="decorative decorative-md">
				<ul class="list">
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-map-marker"></span></div>
							<div class="unit__body"><a class="link-default" href="#">2130 Washington Street, New York, NY 87654</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-phone"></span></div>
							<div class="unit__body"><a class="link-default" href="callto:#">1-800-7658-321</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-email-outline"></span></div>
							<div class="unit__body"><a class="link-default" href="mailto:#">mail@demolink.org</a></div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="cell-sm-6">
			<h6>Norwalk Office</h6>
			<div class="decorative decorative-md">
				<ul class="list">
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-map-marker"></span></div>
							<div class="unit__body"><a class="link-default" href="#">8892 Mayfair St., Norwalk, CT 06851</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-phone"></span></div>
							<div class="unit__body"><a class="link-default" href="callto:#">1-800-8765-098</a></div>
						</div>
					</li>
					<li>
						<div class="unit unit-horizontal unit-spacing-xxs unit-middle">
							<div class="unit__left"><span class="icon icon-xss icon-secondary mdi mdi-email-outline"></span></div>
							<div class="unit__body"><a class="link-default" href="mailto:#">mail@demolink.org</a></div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>

views/_section/_footer-copyright.php
<?php
/**
 * @var \yii\web\View $this
 * @var boolean $isHome
 */
?>
<div class="block-bottom text-sm-right"><a class="brand-name" href="/">
        <img src="/images/brand.png" width="146" height="24" alt=""></a>
    <p class="small">&#169; <span id="copyright-year"></span> Все права защищены
        <!--        <a class="link-default" href="/site/terms-of-use.html">Terms of Use</a> and <a class="link-default" href="/site/privacy-policy.html">Privacy Policy</a>-->
        <?php //if ($isHome): ?>
        <!--    More <a rel="nofollow"-->
        <!--            href="http://www.templatemonster.com/category.php?category=214&type=1"-->
        <!--            target="_blank">Garden Design Templates at TemplateMonster.com</a>-->
        <?php //endif; ?>
    </p>
</div>

views/_section/_footer-menu.php
<?php
use yii\widgets\Menu;

?>
<div class="cell-sm-12">
	<h5>Useful Links</h5>
	<div class="divider divider-3"></div>
	<div class="range range-30">
		<div class="cell-sm-12">
			<?= Menu::widget([
				'items' => [
					['label' => 'About Us', 'url' => ['site/about']],
					['label' => 'Works', 'url' => ['pages/gridgallery']],
					['label' => 'Production', 'url' => ['product/production']],
					['label' => 'Careers', 'url' => ['site/careers']],
					['label' => 'Products', 'url' => ['/site/product-catalog.html']],
					['label' => 'Blog', 'url' => ['news/index']],
				],
				'encodeLabels' => false,
				'options' => array( 'class' => 'list-marked list-marked-1 list-double')
			]);
			?>
		</div>
	</div>
</div>

views/_section/_footer-tags.php
<div class="cell-sm-12">
	<h5>Tags</h5>
	<div class="divider divider-3"></div>
	<ul class="list-tags list-tags-secondary">
		<li><a href="#">Lawn</a></li>
		<li><a href="#">Landscape</a></li>
		<li><a href="#">Statistics</a></li>
		<li><a href="#">News</a></li>
		<li><a href="#">Production</a></li>
		<li><a href="#">GardenLand</a></li>
		<li><a href="#">Partnership</a></li>
	</ul>
</div>

views/_section/_header.php
<header class="section page-header">
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
        <?php if ($isHome): ?>
            <nav class="rd-navbar rd-navbar-default rd-navbar-default-top-panel" data-sm-stick-up-offset="1px"
                 data-md-stick-up-offset="44px" data-lg-stick-up-offset="70px" data-layout="rd-navbar-fixed"
                 data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fullwidth"
                 data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed"
                 data-lg-layout="rd-navbar-static" data-sm-stick-up="true" data-md-stick-up="true"
                 data-lg-stick-up="true">
                <!-- RD Navbar Top Panel-->
                <button class="collapse-toggle" data-rd-navbar-toggle=".rd-navbar-top-panel"><span
                            class="toggle-icon"></span></button>

                <?= $this->render('../_section/_top_panel_home.php') ?>

                <div class="rd-navbar-outer outer-2">
                    <div class="rd-navbar-inner">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-cell rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav"><span
                                        class="toggle-icon"></span></button>
                            <!-- RD Navbar Brand--><a class="rd-navbar-brand" href="./"><img class="brand-mini"
                                                                                             src="/images/brand-mini.png"
                                                                                             width="180" height="33"
                                                                                             alt=""></a>
                        </div>

                        <?= $this->render('../_section/_menu.php') ?>

                        <?php
                        //echo $this->render('../_section/_search.php')
                        ?>

                    </div>
                </div>
            </nav>
        <?php else : ?>
            <nav class="rd-navbar rd-navbar-transparent" data-sm-stick-up-offset="1px" data-md-stick-up-offset="92px"
                 data-lg-stick-up-offset="54px" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
                 data-md-layout="rd-navbar-fullwidth" data-md-device-layout="rd-navbar-fixed"
                 data-lg-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-sm-stick-up="true"
                 data-md-stick-up="true" data-lg-stick-up="true">
                <!-- RD Navbar Top Panel-->
                <button class="collapse-toggle" data-rd-navbar-toggle=".rd-navbar-top-panel"><span
                            class="toggle-icon"></span></button>

                <?= $this->render('../_section/_top_panel_other.php') ?>

                <div class="rd-navbar-outer outer-transparent">
                    <div class="rd-navbar-inner">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-cell rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav"><span
                                        class="toggle-icon"></span></button>
                            <!-- RD Navbar Brand--><a class="rd-navbar-brand" href="./"><img class="brand-normal"
                                                                                             src="/images/brand.png"
                                                                                             width="169" height="23"
                                                                                             alt=""><img
                                        class="brand-mini" src="/images/brand-mini.png" width="169" height="23" alt=""></a>
                        </div>

                        <?= $this->render('../_section/_menu.php') ?>

                        <?php
                        //echo $this->render('../_section/_search.php')
                        ?>

                    </div>
                </div>
            </nav>
        <?php endif; ?>
    </div>
</header>

views/_section/_map-locations.php
<section class="section">
	<div class="rd-google-map rd-google-map__model" data-styles="" data-zoom="4" data-x="60.9874068" data-y="40.643180">
		<ul class="map_locations">
			<li data-y="51.520014" data-x="-0.128383">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
			<li data-y="50.458814" data-x="30.5471116">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
			<li data-y="41.897721" data-x="12.498226">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
			<li data-y="25.604206" data-x="55.271260">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
			<li data-y="28.622246" data-x="77.210013">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
			<li data-y="22.416614" data-x="114.106692">
				<p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
			</li>
		</ul>
	</div>
</section>

views/_section/_page-loader.php
<div class="page-loader">
	<div>
		<div class="page-loader-body">
			<div class="cssload-loader">
				<div class="cssload-inner cssload-one"></div>
				<div class="cssload-inner cssload-two"></div>
				<div class="cssload-inner cssload-three"></div>
			</div>
		</div>
	</div>
</div>

views/_section/_photo-swipe-gallery.php
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="pswp__bg"></div>
	<div class="pswp__scroll-wrap">
		<div class="pswp__container">
			<div class="pswp__item"></div>
			<div class="pswp__item"></div>
			<div class="pswp__item"></div>
		</div>
		<div class="pswp__ui pswp__ui--hidden">
			<div class="pswp__top-bar">
				<div class="pswp__counter"></div>
				<button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
				<button class="pswp__button pswp__button--share" title="Share"></button>
				<button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
				<button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
				<div class="pswp__preloader">
					<div class="pswp__preloader__icn">
						<div class="pswp__preloader__cut">
							<div class="pswp__preloader__donut"></div>
						</div>
					</div>
				</div>
			</div>
			<div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
				<div class="pswp__share-tooltip"></div>
			</div>
			<button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
			<button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
			<div class="pswp__caption">
				<div class="pswp__caption__cent"></div>
			</div>
		</div>
	</div>
</div>

views/_section/_search.php
<!-- RD Navbar Panel Right-->
<div class="rd-navbar-cell rd-navbar-panel-right">
	<!-- Search toggle-->
	<button class="search-toggle" data-rd-navbar-toggle=".rd-navbar-search"><span class="toggle-icon"></span></button>
	<!-- Search-->
	<div class="rd-navbar-search">
		<form class="rd-search" action="/site/search-results.html" data-search-live="rd-search-results-live" method="GET">
			<div class="form-wrap">
				<label class="form-label form-label" for="rd-navbar-search-form-input">Type and hit enter...</label>
				<input class="rd-navbar-search-form-input form-input" id="rd-navbar-search-form-input" type="text" name="s" autocomplete="off">
				<button class="button-submit fa fa-search" type="submit"></button>
				<div class="rd-search-results-live" id="rd-search-results-live"></div>
			</div>
		</form>
	</div>
</div>

views/_section/_snackbars.php
<div class="snackbars" id="form-output-global"></div>

views/_section/_testimonials.php
<section class="section section-xl bg-image-1 context-dark">
	<div class="relative-block text-center">
		<div class="decorative decorative-lg custom-title">
			<h3 class="decorative-title">Testimonials</h3>
		</div>
		<!-- Owl Carousel-->
		<div class="owl-carousel owl-carousel-numbered owl-carousel-numbered-secondary text-center" data-items="1" data-dots="true" data-nav="false" data-stage-padding="15" data-loop="false" data-margin="30" data-mouse-drag="false" data-animation-in="fadeIn">
			<div class="owl-item">
				<div class="range range-center">
					<div class="cell-sm-9 cell-lg-7 cell-xl-5">
						<blockquote class="quote quote-default quote-secondary">
							<div class="quote-body">
								<div class="icon icon-quote fa-quote-left"></div>
								<p>
									<q>GardenLand is a company that we can rely on.  We often have to react to customer needs quickly and we know that GardenLand will take care of us when we need high-quality landscape design services.</q>
								</p>
							</div>
							<div class="quote-meta">
								<div class="unit unit-spacing-xxs unit-middle unit-vertical text-center">
									<div class="unit__left"><img class="img-circle" src="/images/quote-1-60x60.jpg" alt="" width="60" height="60"/>
									</div>
									<div class="unit__body">
										<cite>Robert Ball</cite><small><span>President of US Landscape Design Corporation,</span><br><span>GardenLand’s partner</span></small>
									</div>
								</div>
							</div>
						</blockquote>
					</div>
				</div>
			</div>
			<div class="owl-item">
				<div class="range range-center">
					<div class="cell-sm-9 cell-lg-7 cell-xl-5">
						<blockquote class="quote quote-default quote-secondary">
							<div class="quote-body">
								<div class="icon icon-quote fa-quote-left"></div>
								<p>
									<q>Wow, I’m so happy with your service. I would just like to say thank you for your prompt and effective landscape design, for your friendly and professional support staff! I will recommend your expert company to all my friends.</q>
								</p>
							</div>
							<div class="quote-meta">
								<div class="unit unit-spacing-xxs unit-middle unit-vertical text-center">
									<div class="unit__left"><img class="img-circle" src="/images/quote-2-60x60.jpg" alt="" width="60" height="60"/>
									</div>
									<div class="unit__body">
										<cite>Joe Sanders</cite><small><span>Web Designer,</span><br><span>GardenLand’s customer</span></small>
									</div>
								</div>
							</div>
						</blockquote>
					</div>
				</div>
			</div>
			<div class="owl-item">
				<div class="range range-center">
					<div class="cell-sm-9 cell-lg-7 cell-xl-5">
						<blockquote class="quote quote-default quote-secondary">
							<div class="quote-body">
								<div class="icon icon-quote fa-quote-left"></div>
								<p>
									<q>I just wanted to let you know that our property has never looked better. What an amazing job your crew does!  You are very professional, hardworking and show great pride in your work.</q>
								</p>
							</div>
							<div class="quote-meta">
								<div class="unit unit-spacing-xxs unit-middle unit-vertical text-center">
									<div class="unit__left"><img class="img-circle" src="/images/quote-4-60x60.jpg" alt="" width="60" height="60"/>
									</div>
									<div class="unit__body">
										<cite>James Johnson</cite><small><span>Businessman,</span><br><span>GardenLand’s regular customer</span></small>
									</div>
								</div>
							</div>
						</blockquote>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

views/_section/_top_panel_home.php
<div class="rd-navbar-outer outer-1 rd-navbar-top-panel">
	<div class="rd-navbar-inner">
		<div class="rd-navbar-cell rd-navbar-brand-default">
			<!-- RD Navbar Brand--><a class="rd-navbar-brand" href="./"><img class="brand-normal" src="/images/brand.png" width="180" height="33" alt=""></a>
		</div>
		<div class="rd-navbar-cell">
			<ul class="navbar-inline-list">
				<li class="rd-navbar-info">
					<div class="icon icon-xs icon-primary mdi mdi-email-outline"></div><a class="link" href="mailto:info@gondik.ru">info@gondik.ru</a>
				</li>
				<li class="rd-navbar-info">
					<div class="icon icon-xs icon-primary mdi mdi-phone"></div><a class="link" href="callto:+79091163758">+7 (909) 116-37-58</a>
				</li>
			</ul>
		</div>
	</div>
</div>

views/_section/_top_panel_other.php
<?php
/**
 * @var \yii\web\View $this
 */

use yii\helpers\Html;

?>
<div class="rd-navbar-outer outer-1 rd-navbar-top-panel">
    <div class="rd-navbar-inner">
        <div class="rd-navbar-cell">
            <ul class="navbar-inline-list">
                <li class="rd-navbar-info">
                    <div class="icon icon-xs mdi mdi-map-marker"></div>
                    <?= Html::a('г.Пермь, ул.Свиязева 43', ['site/contact'],
                        ['class' => 'link']) ?>
                </li>
                <li class="rd-navbar-info">
                    <div class="icon icon-xs icon-primary mdi mdi-email-outline"></div>
                    <a class="link" href="mailto:info@gondik.ru">info@gondik.ru</a>
                </li>
                <li class="rd-navbar-info">
                    <div class="icon icon-xs icon-primary mdi mdi-phone"></div>
                    <a class="link" href="callto:+79091173758">+7 (909) 1163 758</a>
                </li>
                <li class="rd-navbar-info">
                    <div class="icon icon-xs mdi mdi-login"></div>
                    <a class="link login" href="/site/login-register.html">Login/Register</a>
                </li>
            </ul>
        </div>
        <div class="rd-navbar-cell">
            <div class="rd-navbar-social"><a class="link fa fa-facebook" href="#"></a><a class="link fa fa-twitter"
                                                                                         href="#"></a><a
                        class="link fa fa-pinterest" href="#"></a><a class="link fa fa-vimeo" href="#"></a><a
                        class="link fa fa-google" href="#"></a><a class="link fa fa-rss" href="#"></a></div>
        </div>
    </div>
</div>