controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionRobots(){
        $this->layout = false;
        if (Yii::$app->params['env']!='prod'){
            return $this->render('robots_none');
        } else {
            return $this->render('robots');
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title = 'Home';
        $this->view->params['homepage'] = true;
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $this->view->title = 'Contacts';
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact/index', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about/index');
    }

    /**
     * Displays mission page.
     *
     * @return string
     */
    public function actionMission()
    {
        return $this->render('mission/index');
    }

    /**
     * Displays careers page.
     *
     * @return string
     */
    public function actionVacancy()
    {
        return $this->render('vacancy/index');
    }

    /**
     * Displays whyus page.
     *
     * @return string
     */
    public function actionWhy()
    {
        $this->view->title = 'Why Us';
        return $this->render('whyus/index');
    }
}

views/site/about/_fabricator.php
<?php
use yii\helpers\Url;
?>
<section class="section section-sm bg-white">
	<div class="shell shell-fluid">
		<div class="range range-xl-condensed range-30">
			<div class="cell-sm-12 cell-xl-10 cell-xl-preffix-1">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">A Few Words About GardenLand</h3>
					<div class="range range-xl-condensed range-justify range-40">
						<div class="cell-md-6 cell-xl-6">
							<p>Over the last 13 years, GardenLand has created numerous award-winning luxury outdoor living areas. In our time we’ve seen the traditional landscaping and outdoor living evolve from verandas into outdoor spaces.</p>
							<p>It blurred the distinction between inside and outside. GardenLand has also evolved. What started as a garden and landscape design company has expanded to now include renovation, construction, interior design and landscape architecture. This allows us to create designs that seamlessly blend the architecture of your home into stunning outdoor rooms and entertaining spaces.</p><a class="button button-primary" href="<?= Url::toRoute(['site/mission']) ?>">View our mission</a>
						</div>
						<div class="cell-md-5 cell-xl-5">
							<div class="progress-linear">
								<div class="progress-header">
									<div><span>Landscape Ideas</span></div>
									<div><span class="text-bold progress-value">70</span></div>
								</div>
								<div class="progress-bar-linear-wrap">
									<div class="progress-bar-linear"></div>
								</div>
							</div>
							<div class="progress-linear">
								<div class="progress-header">
									<div><span>Landscape Maintenance</span></div>
									<div><span class="text-bold progress-value">92</span></div>
								</div>
								<div class="progress-bar-linear-wrap">
									<div class="progress-bar-linear"></div>
								</div>
							</div>
							<div class="progress-linear">
								<div class="progress-header">
									<div><span>Architectural Design Coordination</span></div>
									<div><span class="text-bold progress-value">31</span></div>
								</div>
								<div class="progress-bar-linear-wrap">
									<div class="progress-bar-linear"></div>
								</div>
							</div>
							<div class="progress-linear">
								<div class="progress-header">
									<div><span>Construction Consultation</span></div>
									<div><span class="text-bold progress-value">65</span></div>
								</div>
								<div class="progress-bar-linear-wrap">
									<div class="progress-bar-linear"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

views/site/about/_our-history.php
<section class="section section-sm bg-gray">
	<div class="shell shell-fluid">
		<div class="range range-xl-condensed range-30">
			<div class="cell-lg-6 cell-xl-5 cell-xl-preffix-1">
				<div class="image-wrapper-2"><img src="/images/about-1-480x280.jpg" alt="" width="480" height="280"/><img src="/images/about-2-480x280.jpg" alt="" width="480" height="280"/><img src="/images/about-3-480x280.jpg" alt="" width="480" height="280"/>
				</div>
			</div>
			<div class="cell-lg-5 cell-xl-4 cell-lg-preffix-1">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">Our History</h3>
					<ul class="timeline">
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2003</p>
							</div>
							<div class="timeline-item-body">
								<p>GardenLand was founded in New York in 2003.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2004</p>
							</div>
							<div class="timeline-item-body">
								<p>We introduced new works and projects based on  the history of landscape design.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2006</p>
							</div>
							<div class="timeline-item-body">
								<p>We opened our first office in Indiana in 2006 to support the increasing demand for landscape design.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2007</p>
							</div>
							<div class="timeline-item-body">
								<p>Our team of designers created their first  commercial landscape.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2008</p>
							</div>
							<div class="timeline-item-body">
								<p>New offices open in Pennsylvania and company employment reaches 100 people for the first time.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2009</p>
							</div>
							<div class="timeline-item-body">
								<p>We start our partnership with external design firms for numerous projects and also offer an in-house architectural design team.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2011</p>
							</div>
							<div class="timeline-item-body">
								<p>GardenLand had more than 40 projects under construction in 2011.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2012</p>
							</div>
							<div class="timeline-item-body">
								<p>Philip Spencer becomes a part of our team.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2013</p>
							</div>
							<div class="timeline-item-body">
								<p>A 10th Anniversary celebration is held with employees, families, and customers at the Company headquarters.</p>
							</div>
						</li>
						<li class="timeline-item">
							<div class="timeline-item-header">
								<p>2016</p>
							</div>
							<div class="timeline-item-body">
								<p>GardenLand has completed an impressive list of projects performed in more than 15 states.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

views/site/about/_our-team.php
<section class="section section-sm bg-white">
	<div class="shell shell-fluid">
		<div class="range range-xl-condensed range-center">
			<div class="cell-sm-12 cell-xl-10">
				<div class="decorative decorative-lg">
					<h3 class="decorative-title">Our Team</h3>
				</div>
				<div class="range range-40 range-justify">
					<div class="cell-sm-6 cell-md-3 cell-xl-3">
						<div class="thumbnail-custom thumbnail-type-1">
							<figure><img src="/images/team-1-340x340.jpg" alt="" width="340" height="340"/>
							</figure>
							<div class="caption">
								<div class="decorative decorative-md">
									<h5 class="decorative-title caption-title"><a href="#">Adam Hamilton</a></h5>
									<p class="caption-subtitle">CEO</p>
									<p class="caption-description">Adam is a veteran in this landscaping and exterior design business. Starting off in the industry with mowing neighbor’s lawns in high school, his career climaxed when he founded the GardenLand.</p>
								</div>
							</div>
						</div>
					</div>
					<div class="cell-sm-6 cell-md-3 cell-xl-3">
						<div class="thumbnail-custom thumbnail-type-1">
							<figure><img src="/images/team-2-340x340.jpg" alt="" width="340" height="340"/>
							</figure>
							<div class="caption">
								<div class="decorative decorative-md">
									<h5 class="decorative-title caption-title"><a href="#">Philip Spencer</a></h5>
									<p class="caption-subtitle">Head of Innovation</p>
									<p class="caption-description">This far Philip has been devoting himself for more than twenty-five years, successfully practicing and achieving some great feats in architecture, design and construction.</p>
								</div>
							</div>
						</div>
					</div>
					<div class="cell-sm-6 cell-md-3 cell-xl-3">
						<div class="thumbnail-custom thumbnail-type-1">
							<figure><img src="/images/team-3-340x340.jpg" alt="" width="340" height="340"/>
							</figure>
							<div class="caption">
								<div class="decorative decorative-md">
									<h5 class="decorative-title caption-title"><a href="#">David Hoffman</a></h5>
									<p class="caption-subtitle">Managing Director</p>
									<p class="caption-description">David has 15 years of practical experience in all sorts of design at hand, including the interior design works and project management processes.</p>
								</div>
							</div>
						</div>
					</div>
					<div class="cell-sm-6 cell-md-3 cell-xl-3">
						<div class="thumbnail-custom thumbnail-type-1">
							<figure><img src="/images/team-4-340x340.jpg" alt="" width="340" height="340"/>
							</figure>
							<div class="caption">
								<div class="decorative decorative-md">
									<h5 class="decorative-title caption-title"><a href="#">Richard Contreras</a></h5>
									<p class="caption-subtitle">Leading Landscape Designer</p>
									<p class="caption-description">Richard is really into creating spaces that are not just unique visually to each project of his clients, but which also do embrace the individual suggestions from the clients.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

views/site/about/index.php
<?php
/**
 * @var \yii\web\View $this
 */
$this->title = 'О нашей компании'
?>

<?= $this->render('../../_section/_breadcrumbs.php') ?>

<!-- A Few Words About Fabricator-->
<?= $this->render('_fabricator.php') ?>

<!-- Our History-->
<?= $this->render('_our-history.php') ?>

<!--Our Management Team-->
<?= $this->render('_our-team.php') ?>